### PR TITLE
Fix NRE

### PR DESCRIPTION
**Pull request by jtorvald**
Fixed two null reference exceptions with uninstantiated arrays / collections

### CODE REVIEW

**Comment by jtorvald** [comment]
@mcatanzariti agree. For me it's a bit searching on what does what and where to change. But with your input I will give it a try :-)

**Comment by mcatanzariti** [comment]
You're right, this library is under documented.
It's in my plans.

However, I hope the architecture and the naming convention is clear enough to help others understand the code

**Comment by jtorvald** [comment]
@mcatanzariti yeah it's probably more my experience in this area than the code itself.

**Comment by jtorvald** [comment]
@mcatanzariti I wrote a test and fixed the write methods. I don't do this very often so I hope everything is fine now. Feedback is appreciated.

**Comment by mcatanzariti** [comment]
Thank you for the fix!

**Pull request merged**
