### PR TITLE
More write methods for string and byte string

### LINKED ISSUE #98: Consider adding CborWriter.WriteByteString(int) and WriteByteString(ReadOnlySequence<byte>)
Consider adding the following overloads to `CborWriter.WriteByteString`:

```
        public void WriteByteString(int length)
        {
            WriteInteger(CborMajorType.ByteString, (ulong)length);
        }

        public void WriteByteString(ReadOnlySequence<byte> value)
        {
            WriteInteger(CborMajorType.ByteString, (ulong)value.Length);
            foreach (var segment in value)
            {
                _bufferWriter.Write(segment.Span);
            }
        }
```

Both would be really useful for writing cbor where the entire byte string to be written is not in currently in memory / in one consecutive slice of memory. This is for example the case when the byte string to be written is from a file where the length is known in advance, but where the content is not loaded to memory.

### PR DESCRIPTION
**Pull request by rmja**
This fixes #98

### CODE REVIEW

**Comment by mcatanzariti** [comment]
You miss a test for the first commit (WriteByteString with sequence) !

**Comment by rmja** [comment]
@mcatanzariti done.

**Comment by rmja** [comment]
I went with the WriteByteStringSize instead of WriteByteStringLength because it seems as if "size" is throughout the library.

**Comment by mcatanzariti** [comment]
Thanks a lot for your contributions !

**Pull request merged**
